name: otel-services-evdb-quick-start
services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    container_name: evdb-jaeger-quick-start
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4318:4318
      - 4317:4317
    restart: unless-stopped
    
  aspire-dashboard:
    # https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: evdb-aspire-dashboard-quick-start
    ports:
      - 18888:18888
      - 18889:18889
      # - 4317:18889
    environment:
      - DASHBOARD__TELEMETRYLIMITS__MAXLOGCOUNT=1000
      - DASHBOARD__TELEMETRYLIMITS__MAXTRACECOUNT=1000
      - DASHBOARD__TELEMETRYLIMITS__MAXMETRICCOUNT=1000
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    restart: unless-stopped
    